ALTER TABLE "Restaurant" ADD COLUMN "autoGenerateEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Restaurant" ADD COLUMN "autoGenerateDay"     INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Restaurant" ADD COLUMN "autoGenerateHour"    INTEGER NOT NULL DEFAULT 8;
