const { Router } = require('express');
const db = require('../lib/db');

const router = Router();

// GET /api/db/businesses
router.get('/', async (req, res) => {
  try {
    if (req.businessId !== undefined) {
      const row = await db.business.findUnique({ where: { id: req.businessId } });
      return res.json(row ? [row] : []);
    }
    const rows = await db.business.findMany({ orderBy: { createdAt: 'desc' } });
    res.json(rows);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// GET /api/db/businesses/:id
router.get('/:id', async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (req.businessId !== undefined && req.businessId !== id)
      return res.status(404).json({ error: 'Not found' });
    const row = await db.business.findUnique({ where: { id } });
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.json(row);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// POST /api/db/businesses
router.post('/', async (req, res) => {
  const { name, cuisineType, location, ownerName, tagline, brandColorPrimary, brandColorAccent,
          brandColorBg, platforms, twinStyle, twinUsecase, ownerScript,
          logoUrl, ownerPortraitUrl, instagramAccessToken, instagramUserId,
          autoPublishEnabled } = req.body;
  if (!name) return res.status(400).json({ error: 'name is required' });
  try {
    const row = await db.business.create({
      data: { name, cuisineType, location, ownerName, tagline, brandColorPrimary, brandColorAccent,
              brandColorBg, platforms, twinStyle, twinUsecase, ownerScript,
              logoUrl, ownerPortraitUrl, instagramAccessToken, instagramUserId,
              autoPublishEnabled: Boolean(autoPublishEnabled) },
    });
    res.status(201).json(row);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// PATCH /api/db/businesses/:id
router.patch('/:id', async (req, res) => {
  const id = Number(req.params.id);
  if (req.businessId !== undefined && req.businessId !== id)
    return res.status(404).json({ error: 'Not found' });
  const allowed = ['name','cuisineType','businessType','location','ownerName','chefName','tagline','loginEmail','brandColorPrimary',
                   'brandColorAccent','brandColorBg','platforms','twinStyle','twinUsecase',
                   'ownerScript','logoUrl','ownerPortraitUrl','instagramAccessToken',
                   'instagramUserId','instagramUrl','facebookPageId','tokenExpiresAt','autoPublishEnabled',
                   'voiceTone','defaultHashtags','includeLocation','ownerVoiceId',
                   'heygenAvatarId','heygenAvatarStyle','twinBackgroundUrl',
                   'autoGenerateEnabled','autoGenerateDay','autoGenerateHour'];
  const data = Object.fromEntries(Object.entries(req.body).filter(([k]) => allowed.includes(k)));
  try {
    const row = await db.business.update({ where: { id }, data });
    res.json(row);
  } catch (e) {
    if (e.code === 'P2025') return res.status(404).json({ error: 'Not found' });
    res.status(500).json({ error: e.message });
  }
});

// DELETE /api/db/businesses/:id
router.delete('/:id', async (req, res) => {
  const id = Number(req.params.id);
  if (req.businessId !== undefined && req.businessId !== id)
    return res.status(404).json({ error: 'Not found' });
  try {
    await db.business.delete({ where: { id } });
    res.json({ success: true });
  } catch (e) {
    if (e.code === 'P2025') return res.status(404).json({ error: 'Not found' });
    res.status(500).json({ error: e.message });
  }
});

module.exports = router;
